### ISSUE TITLE
failed at final build via `cargo install` but build-from-source works fun

### ISSUE THREAD

**Issue by AndyJado** [SergeyKasmy/fetcher#2]
`failed to run custom build command for fetcher v0.12.`

**Comment by SergeyKasmy** [comment]
I'm looking into it... Seems like the build script is failing. I think it's because I'm trying to get the active git branch from within it and you are installing it with cargo install, so it has none?

**Comment by AndyJado** [comment]
```sh
could not find repository from '/root/.cargo/registry/src/github.com-1ecc6299db9ec823/fetcher-0.12.0'; class=Repository (6); code=NotFound (-3)', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/fetcher-0.12.0/build.rs:14:18
```

**Comment by SergeyKasmy** [comment]
Pushed the fix to crates.io, everything should be working now. Thanks for the first issue!
